#!/usr/bin/env bash
echo "Set local variables before start Worker"
#echo "don't forget this command: chmod +x set_locals.sh"

export AKKA_SEED_NODES='localhost:2551,localhost:2552'
echo "AKKA_SEED_NODES=$AKKA_SEED_NODES"

export AKKA_REMOTING_BIND_HOST='localhost'
echo "AKKA_REMOTING_BIND_HOST=$AKKA_REMOTING_BIND_HOST"

export AKKA_REMOTING_BIND_PORT='52551'
echo "AKKA_REMOTING_BIND_PORT=$AKKA_REMOTING_BIND_PORT"

export AKKA_ACTOR_SYSTEM_NAME='FileIOClusterSystem'
echo "AKKA_ACTOR_SYSTEM_NAME=$AKKA_ACTOR_SYSTEM_NAME"



export CASSANDRA_ADDRESS='localhost'
echo "CASSANDRA_ADDRESS=$CASSANDRA_ADDRESS"

export CASSANDRA_PORT='9042'
echo "CASSANDRA_PORT=$CASSANDRA_PORT"

export CASSANDRA_KEYSPACE='direct_tv'
echo "CASSANDRA_KEYSPACE=$CASSANDRA_KEYSPACE"

export CASSANDRA_LOGIN=''
echo "CASSANDRA_LOGIN=$CASSANDRA_LOGIN"

export CASSANDRA_PASSWORD=''
echo "CASSANDRA_PASSWORD=$CASSANDRA_PASSWORD"



export KAMON_STATSD_HOSTNAME='127.0.0.1'
echo "KAMON_STATSD_HOSTNAME=$KAMON_STATSD_HOSTNAME"

export KAMON_STATSD_PORT=8125
echo "KAMON_STATSD_PORT=$KAMON_STATSD_PORT"